---
- name: Launch docker-compose with Prometheus and Grafana
  hosts: localhost
  become: yes
  tasks:
    - name: Create docker network
      community.docker.docker_network:
        name: new-net
        driver_options:
          com.docker.network.bridge.name: br-new-net

    - name: Create prometheus folder
      ansible.builtin.file:
        path: /home/vagrant/prometheus
        state: directory

    - name: Gathering facts
      setup:

    - name: Copy Jinja template to prometheus configuration
      template:
        src: /home/vagrant/prometheus.j2
        dest: /home/vagrant/prometheus/prometheus.yml

    - name: Start docker compose with Prometheus and Grafana
      community.docker.docker_compose:
        project_src: .
        state: present
