---
- name: Install docker
  import_playbook: docker-install.yml

- name: Install node-exporter
  import_playbook: node-exporter.yml

- name: Launch Prometheus and Grafana
  import_playbook: launch-docker-compose.yml
