---
- name: Launch all playbooks
  hosts: localhost
  become: yes
  tasks:
    - include_tasks: docker-install.yml
    - include_tasks: node-exporter.yml
    - include_tasks: launch-docker-compose.yml
